### PR TITLE
Add support for arrow functions

### PR DESCRIPTION
**Pull request by luki-**

### CODE REVIEW

**Comment by luin** [comment]
Could you please add some tests for the changes?

**Comment by luki-** [comment]
Sure, done. I had to modify node version for Travis, as the `0.12` does not support arrow functions.

**Comment by kirmanie** [comment]
Hi, any reason all progress halted on this PR for so long? I'd love this feature. I'm willing to help in whatever way.

**Comment by luin** [comment]
Sorry for the delay! This pull request has been released in v5.0.

**Pull request merged**
